import "@/styles/global.css";
import { Rubik } from "next/font/google";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { GlobalContextProvider } from "@/utils/useContext";
import Navbar from "@/components/Navbar";

export const revalidate = 0;

const sans = Rubik({
  subsets: ["latin"],
  weight: ["variable"],
});

export const metadata = {
  title: "Udemo-The learning app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return (

    
    <html lang="en">
      <body className={sans.className}>
        <GlobalContextProvider>
          <Navbar user={user} />
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
